public class AffStation
{
    public string affiliatedbasin { get; set; }
    public string affiliatedsubsidiarybasinrivercode { get; set; }
    public string affiliatedsubsubsidiarybasinrivercode { get; set; }
    public string alertlevel1 { get; set; }
    public string alertlevel2 { get; set; }
    public string alertlevel3 { get; set; }
    public string areacode { get; set; }
    public string basinidentifier { get; set; }
    public string brittlenessstatus { get; set; }
    public string cardrivedistanceinhours { get; set; }
    public string cityelectricitysupplystatus { get; set; }
    public string constructionmanagement { get; set; }
    public string crossriverstructuresnameofequipment { get; set; }
    public string datacollectionfrequecy { get; set; }
    public string datasubmitted { get; set; }
    public string drainagestatus { get; set; }
    public string ecologicalenvironmentmonitoring { get; set; }
    public string elevationofwaterlevelzeropoint { get; set; }
    public string englishaddress { get; set; }
    public string englishname { get; set; }
    public string englishrivername { get; set; }
    public string equipmentstatus { get; set; }
    public string equipmentstatusoncrossriverstructures { get; set; }
    public string establishdate { get; set; }
    public string floodpreventionpurpose { get; set; }
    public string highsedimentstatus { get; set; }
    public string hydrofacilitymanagement { get; set; }
    public string hydrologicalmonitoringpurpose { get; set; }
    public string lightningstatus { get; set; }
    public string locationaddress { get; set; }
    public string locationbytwd67_xy { get; set; }
    public string locationbytwd97_xy { get; set; }
    public string maintaincycle { get; set; }
    public string noperiodicaldatasubmissionreason { get; set; }
    public string normalobservationtype { get; set; }
    public string obervationitems { get; set; }
    public string observationreason { get; set; }
    public string observationstatus { get; set; }
    public string observatoryidentifier { get; set; }
    public string observatoryname { get; set; }
    public string replacestatus { get; set; }
    public string onsitedatacollection { get; set; }
    public string otherrequirement { get; set; }
    public string realtimedatadeliveryfrequency { get; set; }
    public string realtimedatadeliveryfrequencyinflooddefencetime { get; set; }
    public string remarks { get; set; }
    public string rivername { get; set; }
    public string riversectiondepositionanderosionchange { get; set; }
    public string shortobservationtype { get; set; }
    public string solarpotentialdemage { get; set; }
    public string solarstatus { get; set; }
    public string solarwatt { get; set; }
    public string stealstatus { get; set; }
    public string straightriverstatus { get; set; }
    public string subsidencestatus { get; set; }
    public string sunlightcoveragestatus { get; set; }
    public string sunshinestatus { get; set; }
    public string tidestatus { get; set; }
    public string transmissionequipment { get; set; }
    public string verticaldatumsourcestatus { get; set; }
    public string walkdistanceinhours { get; set; }
    public string waterdrawstatus { get; set; }
    public string waterresourcedistrictidentifier { get; set; }
    public string wirelesstransmissiontype { get; set; }
}
